---

- name: plan nomad job
  shell: /usr/local/bin/nomad plan /usr/local/nomad-demo/job/{{job}}.{{version}}.nomad
  register: plan_result
  failed_when: plan_result.rc != 0 and plan_result.rc != 1

- name: run nomad job
  shell: /usr/local/bin/nomad run /usr/local/nomad-demo/job/{{job}}.{{version}}.nomad
