---

- name: create /etc/ansible directory
  file: path=/etc/ansible state=directory
  become: true

- name: configure ansible
  template: src=ansible.cfg.j2 dest=/etc/ansible/ansible.cfg mode=0644
  become: true
