---

- name: create nomad user
  user: name=nomad
  become: true

- name: create data directory
  file: path=/var/lib/nomad/server state=directory owner=nomad
  become: true

- name: create configuration directory
  file: path=/etc/nomad.d/server state=directory
  become: true

- name: install configuration file
  template:
    src: config.hcl.j2
    dest: /etc/nomad.d/server/config.hcl
    backup: true
  become: true
  notify: restart nomad server

- name: install systemd config
  template:
    src: systemd_service.j2
    dest: /etc/systemd/system/nomad_server.service
    backup: true
  become: true
  notify: restart nomad server

- name: set NOMAD_ADDR for interactive shells
  template:
    src: nomad.sh.j2
    dest: /etc/profile.d/nomad.sh
    mode: 0755
  become: true

- name: install nomad wrapper
  template:
    src: nomad_wrapper.sh.j2
    dest: /usr/local/bin/nomad
    mode: 0755
  become: true
