---

# Required variables:
#
#       job: name of the nomad job
#       program: name of the Go executable
#

- hosts: nomad_clients,nomad_servers[0]
  tasks:
    - set_fact: timestamp={{ansible_date_time.iso8601}}
    - set_fact: deploy_dir=/usr/local/nomad-demo/{{job}}/{{timestamp}}

- hosts: nomad_clients
  gather_facts: no
  roles:
    - role: basic_deploy
      executable_path: "{{playbook_dir}}/../go/bin/{{program}}"
      job: "{{job}}"
      program: "{{program}}"

- hosts: nomad_servers[0]
  gather_facts: no
  roles:
    - role: nomad_run_job
      job: "{{job}}"
